config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :spots do
    resources :comments, only: [:new, :create, :show]
    collection do
      get :stolen_bike
    end
  end

  resources :comments, only: :destroy

  devise_for :users
  authenticated :user do
    root to: "spots#index", as: :authenticated_root
  end

  unauthenticated do
    root to: "pages#home"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "profile", to: "pages#profile"
  get "about", to: "pages#about"

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :comment, :location, presence: true
  validates :category, presence: true, inclusion: { in: ["Stolen bike", "Accident"] }
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  has_one_attached :photo
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_spot, only: %i[ show edit update destroy ]

  # GET /spots or /spots.json
  def index
    @spot = Spot.new
    @spots = Spot.all
    # The `geocoded` scope filters only spots with coordinates
    @markers = @spots.geocoded.map do |spot|
      {
        lat: spot.latitude,
        lng: spot.longitude,
        category: spot.category,
        info_window: render_to_string(partial: "info_window", locals: {spot: spot}),
        # image_url: helpers.asset_url("circle_accident.png")
        image_url: category_marker(spot)
      }
    end


    @stolen_bike_count = Spot.all.where(category: "Stolen bike").count
    @accident_count = Spot.all.where(category: "Accident").count

  end

  def stolen_bike
    @spots = Spot.all.where(category: "Stolen bike")
    @comment = Comment.new
    # TODO : add --> spot.nearbys(5) to show only nearby spots
  end

  # GET /spots/1 or /spots/1.json
  def show
    @comment = Comment.new
    @comments = Comment.all.where(spot_id: @spot.id)
  end

  # GET /spots/new
  def new
    @spot = Spot.new
  end

  # GET /spots/1/edit
  def edit
  end

  # POST /spots or /spots.json
  def create
    @spot = Spot.new(spot_params)
    @spot.user = current_user
    respond_to do |format|
      if @spot.save
        format.html { redirect_to spot_url(@spot), notice: "Spot was successfully created." }
        format.json { render :show, status: :created, location: @spot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spots/1 or /spots/1.json
  def update
    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to spot_url(@spot), notice: "Spot was successfully updated." }
        format.json { render :show, status: :ok, location: @spot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1 or /spots/1.json
  def destroy
    @spot.destroy

    respond_to do |format|
      format.html { redirect_to spots_url, notice: "Spot was successfully destroyed." }
      format.json { head :no_content }
    end

    def article_params
      params.require(:article).permit(:title, :body, :photo)
    end
  end

  private

  def set_spot
    @spot = Spot.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def spot_params
    params.require(:spot).permit(:comment, :category, :location, :acitve, :user_id, :photo)
  end

  def category_marker(spot)
    if spot.category == "Accident"
      return helpers.asset_url("circle_accident.png")
    else
      return helpers.asset_url("circle_stolen_bike.png")
    end
  end
end

app/views/spots/_form.html.erb
  <%= simple_form_for(@spot)  do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs" >
      <%= f.input :comment, as: :text, input_html: { class: "new-text" } %>
      <%= f.input :category, collection: ["Stolen bike", "Accident"], input_html: { class: "new-text" } %>
      <%= f.input :location, placeholder: 'Location', class: "new-text" , input_html: { "data-target" => "geolocalisation.input" } %>
      <%= f.input :photo, as: :file %>
    </div>
    <div >
      <%= f.button :submit, "SUBMIT", class: "submit-text" %>
    </div>
  <% end %>

app/views/spots/_info_window.html.erb
  <h2><%= spot.category %></h2>
  <p><%= spot.comment %></p>
  <%= link_to "MORE INFO", spot_path(spot) %>

app/views/spots/_info_window_map.html.erb
  <%= link_to "report", new_spot_path %>

app/views/spots/_legend.html.erb
<%# <div class="legend">
    <span><%= image_tag "circle_accident.png"%>
        <%# crash
    </span>
    <span><%= image_tag "circle_stolen_bike.png" %>
        <%# theft
    </span>
</div> %>

app/views/spots/_spot.html.erb
<h2>REPORT</h2>

<div class="spot">
      <div class="photo-position">
      <% if spot.photo.attached? %>
        <%= cl_image_tag spot.photo.key, crop: :fill, class: "photo-fit-card" %>
      <% end %>
      </div>

      <div id="<%= dom_id spot %>", class= "spot-container">

        <p>
          <div class="spot-title">Description</div>
          <div class="spot-box"><%= spot.comment %></div>
        </p>

        <p>
          <div class="spot-title">Category</div>
          <div class="spot-box"><%= spot.category %></div>
        </p>

        <p>
          <div class="spot-title">Location</div>
          <div class="spot-box"><%= spot.location %></div>
        </p>

      </div>
</div>

app/views/spots/_spot_near.html.erb
<div class="spot-near" data-target="nearme.element">
   <div class="spot-near-container">
    <%@spots.each do |spot| %>
        <%= link_to spot_path(spot) do %>
            <div class="spot-near-item">
                <% if  spot.category == "Accident" %>
                    <%= image_tag("circle_accident.png", size: "16") %>
                <%else%>
                    <%= image_tag("circle_stolen_bike.png", size: "16") %>
                <%end %>
                <%= spot.comment %>
                <div class="spot-location"><%= spot.location %></div>
            </div>
        <%end%>
    <%end%>
    </div>
</div>

app/views/spots/edit.html.erb
<div class="body-container">
    <div class="form-block">
      <div class="form-container">
          <h2>Edit a location</h2>

          <%= render "form", spot: @spot %>


          <div class="form-link">
            <div><%= link_to "Show this spot", @spot, class:"form-link-text" %></div>
            <div><%= link_to "Back to spots", spots_path, class:"form-link-text" %></div>
          </div>
      </div>
    </div>
</div>

app/views/spots/index.html.erb
  <div class="spots-page">
    <%=render "shared/map"%>

  </div>
      <%# <%= render "legend" %>
  <div style="position: absolute; z-index: 1; top: 185px; left: 55px;">
    <%= link_to "REPORT", new_spot_path, class: "new-spot-button"%>
  </div>
  

  <div id="btn-near" style="position: absolute; z-index: 10; top: 185px; right: 55px; cursor:pointer " data-controller="nearme">
    <p class="new-spot-button open-close" style="font-size: 15px" data-action="click->nearme#toggleClass"> NEAR ME</p>
    <%= render "spot_near" %>
  </div>


  <div class="footer">
    <div class="footer-content">
      <ul class="footer-list-left">
        <%date = Date.today%>
        <li class="footer-text">©<%= date.year  %>, ChillWheel</li>
        <li><%= link_to "About", about_path, class: "footer-link" %></li>
        <li><%= link_to "Privacy", "https://ec.europa.eu/info/law/law-topic/data-protection_en", target: "_blank", class: "footer-link" %></li>
        <li><%= link_to "Terms",  "https://www.commissioner.brussels/en/i-am-an-expat/housing/82-housing/104-signing-a-lease", target: "_blank", class: "footer-link" %></li>
      </ul>

      <ul class="footer-list-right">
        <li class="footer-counter"><p>LAST 14 DAYS </p></li>
        <li class="footer-counter-text"><p>TOTAL CRASHES:</p></li>
        <li class="footer-counter-number-crash"><%= @accident_count %></li>
        <li class="footer-counter-text"><p>TOTAL THEFTS:</p></li>
        <li class="footer-counter-number-theft"><%= @stolen_bike_count %></li>
      </ul>
    </div>
  </div>
</div>

app/views/spots/new.html.erb
<div class="background">
  <div class="body-container">
      <div class="form-block">
        <div class="form-container">

          <h2>REPORT</h2>
          <div data-controller=geolocalisation>
            <span data-geolocalisation-target="span"></span>
            <%= render "form", spot: @spot %>
          </div>

          <div class="form-link">
            <%= link_to "BACK TO THE MAP", spots_path, class:"form-link-text" %>
          </div>
        </div>
      </div>
  </div>
</div>

    <%=render "shared/footer"%>

app/views/spots/show.html.erb
<div class="background">
  <div class="body-container">
    <div class="form-block">
      <div class="form-container">
        <div class="spots">
          <%= render @spot %>
        </div>
        <div>
          <%= render "comments/comments" %>
          <br>
        </div>
        <div>
          <%= render "comments/new"%>
          <br>
        </div>
        <div class="form-link">
          <%= link_to "BACK TO THE MAP", spots_path, class:"form-link-text" %>
        </div>
        <div>
        </div>
      </div>
    </div>
  </div>
</div>

    <%=render "shared/footer"%>

app/views/spots/stolen_bike.html.erb
<div class="background">

  <div class="stolenbikes-title">
    <p>STOLEN BIKES LIST</p>
  </div>

  <div class="stolen-bike-container">
      <% @spots.each do |spot| %>
        <%= link_to spot_path(spot) do %>
          <div class="stolen-bike-cards">
          <div class="inside-card-display">
          <div class="left">
          <%#= link_to spot_path(spot) do %>
            <% if spot.photo.attached? %>
              <%= cl_image_tag spot.photo.key, crop: :fill, class: "photo-fit-card-2" %>
            <% end %>
            </div>
            <div class="right">
            <p class="stolen-bike-text">Location:</p>
            <div class= "text-margin"><%=spot.location %></div>
            <p class="stolen-bike-text">Owner:</p>
            <div class= "text-margin"><%=spot.user.username %></div>
            </div>
            </div>
            </div>
        <%end  %>
      <% end %>
  </div>
  <div class="backtomap">
    <%= link_to "BACK TO MAP", spots_path, class:"backtomap-text" %>
  </div>

</div>

  <div class="footer">
      <div class="footer-content">
        <ul class="footer-list-left">
          <%date = Date.today%>
          <li class="footer-text">©<%= date.year  %>, ChillWheel</li>
          <li><%= link_to "About", about_path, class: "footer-link" %></li>
          <li><%= link_to "Privacy", "https://ec.europa.eu/info/law/law-topic/data-protection_en", target: "_blank", class: "footer-link" %></li>
          <li><%= link_to "Terms",  "https://www.commissioner.brussels/en/i-am-an-expat/housing/82-housing/104-signing-a-lease", target: "_blank", class: "footer-link" %></li>
        </ul>
      </div>
    </div>