config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :spots do
    resources :comments, only: [:new, :create, :show]
    collection do
      get :stolen_bike
    end
  end

  resources :comments, only: :destroy

  devise_for :users
  authenticated :user do
    root to: "spots#index", as: :authenticated_root
  end

  unauthenticated do
    root to: "pages#home"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "profile", to: "pages#profile"
  get "about", to: "pages#about"

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
    <div class="footer-content">
      <ul class="footer-list-left">
        <%date = Date.today%>
        <li class="footer-text">©<%= date.year  %>, ChillWheel</li>
        <li><%= link_to "About", "about#pages", class: "footer-link" %></li>
        <li><%= link_to "Privacy", "https://ec.europa.eu/info/law/law-topic/data-protection_en", target: "_blank", class: "footer-link" %></li>
        <li><%= link_to "Terms",  "https://www.commissioner.brussels/en/i-am-an-expat/housing/82-housing/104-signing-a-lease", target: "_blank", class: "footer-link" %></li>
      </ul>
    </div>
  </div>

app/views/shared/_map.html.erb
<div class="map-co"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <div id="logo">Chill'Wheel</div>
    <% end %>

    <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
           <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, height: 40, width: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true %>
            <% else%>
            <%= image_tag "https://img.icons8.com/ios-filled/512/gender-neutral-user.png", height: 40, width: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end%>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%# <p> <%= current_user.username %>
              <%= link_to "Stolen Bikes List",  stolen_bike_spots_path, class: "dropdown-item" %>
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log Out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="button">
            <%= link_to "LOGIN", new_user_session_path, class: "text-button" %>
          </li>
        <%end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<%= simple_form_for :search, method: :get do |f| %>
<%= f.input :location,
  input_html: {data: {location_autocomplete_target: "location"}},
  wrapper_html: {data: {controller: "location-autocomplete", location_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
%>
<% end %>